version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: US/Central
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: US/Central
