name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: v1/${{ runner.os }}/java-8/${{ hashFiles('**/package-lock.json') }}
          restore-keys: v1/${{ runner.os }}/java-8/
      - run: yarn
      - run: npx percy exec -- mvn test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
